title: 叨叨
description: 读书，搞机与其他
author: 阿Ben同学
github: https://ben7z.github.io
about: 乏善可陈
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ben7z"
    - icon: fa-github
      link: "https://ben7z.github.io"

urls:
    - text: About Me
      url: /about/

url: "https://ben7z.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
